// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using capstone_v2;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20191015173732_ChangedNames")]
    partial class ChangedNames
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Capstone_V2.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Clicker")
                        .HasColumnType("json");

                    b.Property<string>("Counter")
                        .HasColumnType("json");

                    b.Property<DateTime>("Date");

                    b.Property<string>("EspressoMachine")
                        .HasColumnType("json");

                    b.Property<string>("Keurig")
                        .HasColumnType("json");

                    b.Property<string>("Worker")
                        .HasColumnType("json");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Capstone_V2.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Email");

                    b.Property<string>("ProperName");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Capstone_V2.Models.Player_Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GameId");

                    b.Property<int?>("PlayerId");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Player_Games");
                });

            modelBuilder.Entity("Capstone_V2.Models.Player_Game", b =>
                {
                    b.HasOne("Capstone_V2.Models.Game", "Game")
                        .WithMany("Player_Games")
                        .HasForeignKey("GameId");

                    b.HasOne("Capstone_V2.Models.Player", "Player")
                        .WithMany("Player_Games")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
