// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using capstone_v2;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Capstone_V2.Models.PlayerStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<int>("GrossInventory");

                    b.Property<string>("HandleUserName");

                    b.Property<int>("InventoryPerSecond");

                    b.Property<string>("ProperName");

                    b.Property<int>("TotalInventory");

                    b.Property<int>("TotalInventorySpent");

                    b.Property<int>("TotalNumberOfObject1");

                    b.Property<int>("TotalNumberOfObject2");

                    b.Property<int>("TotalNumberOfObject3");

                    b.Property<int>("TotalNumberOfObject4");

                    b.HasKey("Id");

                    b.ToTable("PlayerStats");
                });

            modelBuilder.Entity("Capstone_V2.Models.SingleGameSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateSaved");

                    b.Property<int>("GrossInventory");

                    b.Property<int>("InventoryPerSecond");

                    b.Property<int>("TotalInventory");

                    b.Property<int>("TotalInventorySpent");

                    b.Property<int>("TotalNumberOfObject1");

                    b.Property<int>("TotalNumberOfObject2");

                    b.Property<int>("TotalNumberOfObject3");

                    b.Property<int>("TotalNumberOfObject4");

                    b.HasKey("Id");

                    b.ToTable("SingleGameSave");
                });
#pragma warning restore 612, 618
        }
    }
}
